[phases.setup]
  nixPkgs = ["python310Packages.pip", "python310Packages.python-telegram-bot", "python310Packages.matplotlib", "python310Packages.requests", "freetype", "libpng"]

[phases.install]
  cmds = []

[phases.build]
  cmds = []

[start]
  cmd = "python3.10 main.py"
