[phases.setup]
  nixPkgs = ["python310", "python310Packages.pip", "python310Packages.python-telegram-bot", "python310Packages.matplotlib", "python310Packages.requests", "freetype", "libpng"]

[phases.install]
  cmds = ["export PATH=/nix/store/*/bin:$PATH"]

[phases.build]
  cmds = []

[start]
  cmd = "/nix/store/*/bin/python3.10 main.py"
