[phases.setup]
  nixPkgs = ["python310", "freetype", "libpng"]

[phases.install]
  cmds = ["python3.10 -m pip install -r requirements.txt"]

[phases.build]
  cmds = []

[start]
  cmd = "python3.10 main.py"
